apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-nginx
  template:
    metadata:
      labels:
        app: sample-nginx
    spec:
      containers:
        - name: nginx
          image: rojaldo/sample-nginx:latest
          ports:
            - containerPort: 80