apiVersion: v1
kind: Service
metadata:
  name: sample-nginx-service
spec:
  selector:
    app: sample-nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 8086        # Puerto dentro del clúster
      targetPort: 80    # Puerto interno del contenedor
