FROM --platform=x86_64 alpine:3.21.3
LABEL maintainer="My Name"
LABEL description="Sample Dockerfile for a simple Alpine container"
# Install necessary packages to run python
RUN apk update && \
    apk add --no-cache python3 py3-pip && \
    rm -rf /var/cache/apk/*

# Install bin/bash for compatibility
RUN apk add --no-cache bash

# copy necessary files
COPY ./content /app
# Set the working directory
WORKDIR /app
# run python to display a message
CMD ["python3", "app.py"]