FROM --platform=x86_64 ubuntu:25.04
LABEL maintainer="My Name"
LABEL description="Sample Dockerfile for a simple Python container"

# install necessary packages to run figlet
RUN apt-get update && \
    apt-get install -y figlet && \
    rm -rf /var/lib/apt/lists/*

ENV FIGLET_FONT=standard
ENV MESSAGE="Hello, World!"

CMD figlet -f $FIGLET_FONT "$MESSAGE"